---
- name: Test and validation for cv_facts module.
  hosts: cvp
  connection: local
  gather_facts: no
  collections:
    - arista.cvp

  tasks:
    - name: "Gather CVP facts {{inventory_hostname}}"
      cv_facts:
      register: cv_facts

    - name: "Print out facts from CVP"
      debug:
        msg: "{{cv_facts}}"
