#!/bin/bash

TARGET="4.24.0F"
TARGET_FILENAME="vEOS-lab-4.24.0F.swi"
TARGET_URL="http://10.34.0.254/images/vEOS-lab-4.24.0F.swi"

CONFIG_URL="http://10.34.0.254:8080/dynconfig"

# Get current switch EOS version
CURRENT=$(/bin/FastCli -c "show version" | grep "Software image version" | /bin/cut -d":" -f2 | /bin/tr -d " ")

# Get systemmac and transform like  5054.0000.3131 into 50:54:00:00:31:31
SYSTEMMAC=$(/bin/FastCli -c "show version" | grep "System MAC address" | /bin/cut -d":" -f2 | /bin/tr -d " ." | /bin/sed 's/..\B/&:/g')

#Upgrade/Downgrade if needed
if [ "$CURRENT" != "$TARGET" ]
then
/bin/FastCli -p 15 -c "copy $TARGET_URL flash:$TARGET_FILENAME"
echo -e "configure\nboot system flash:$TARGET_FILENAME" | /bin/FastCli -p 15
fi

#Get switch config dynamically generated by the server based on system mac
/bin/curl -o "/mnt/flash/startup-config" -H "X-Arista-SystemMAC: $SYSTEMMAC" $CONFIG_URL
